name: CI

on:
  push:
    branches:
      - '**'

jobs:
  check-rust:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - run: cargo clippy

  test-rust:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x86_64
            os: windows-latest
          - name: Linux x86_64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
    - name: Show rust version
      run: rustc --version
    - name: install swiftshader
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        set -e
        mkdir -p swiftshader
        curl -LsSf https://github.com/gfx-rs/ci-build/releases/latest/download/swiftshader-linux-x86_64.tar.xz | tar -xf - -C swiftshader
        echo "VK_ICD_FILENAMES=$PWD/swiftshader/vk_swiftshader_icd.json" >> "$GITHUB_ENV"
    - name: install llvmpipe, vulkan sdk
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        set -e
        sudo apt-get update -y -qq
        # vulkan sdk
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
        sudo apt-get update
        sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev vulkan-sdk
    - run: cargo run -- sample.wgsl
    - name: Print adapter info
      run: cargo run -- --adapter-info
    - run: WGPU_BACKEND=gl ./run-wgpu-tests.sh
      if: matrix.os == 'ubuntu-latest'
    - name: Run test suite
      run: SHOW_ERRORS=1 ./run-wgpu-tests.sh
      shell: bash

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
